package client.demo.dao;

import client.demo.model.HotNews;
import client.demo.model.HotNewsExample;
import client.demo.model.HotNewsWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int countByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int deleteByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int insert(HotNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int insertSelective(HotNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    List<HotNewsWithBLOBs> selectByExampleWithBLOBs(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    List<HotNews> selectByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    HotNewsWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByExampleSelective(@Param("record") HotNewsWithBLOBs record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") HotNewsWithBLOBs record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByExample(@Param("record") HotNews record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByPrimaryKeySelective(HotNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(HotNewsWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    int updateByPrimaryKey(HotNews record);
}