package client.demo.dao;

import client.demo.model.HotNews;
import client.demo.model.HotNewsExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface HotNewsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int countByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int deleteByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int insert(HotNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int insertSelective(HotNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    List<HotNews> selectByExampleWithBLOBs(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    List<HotNews> selectByExample(HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    HotNews selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByExampleSelective(@Param("record") HotNews record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByExampleWithBLOBs(@Param("record") HotNews record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByExample(@Param("record") HotNews record, @Param("example") HotNewsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByPrimaryKeySelective(HotNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByPrimaryKeyWithBLOBs(HotNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_hot_news
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    int updateByPrimaryKey(HotNews record);
}