package client.demo.model;

public class HotNewsWithBLOBs extends HotNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.imageurl
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    private String imageurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.extra1
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    private String extra1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.extra2
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    private String extra2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.url
     *
     * @return the value of t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.url
     *
     * @param url the value for t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.imageurl
     *
     * @return the value of t_hot_news.imageurl
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public String getImageurl() {
        return imageurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.imageurl
     *
     * @param imageurl the value for t_hot_news.imageurl
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public void setImageurl(String imageurl) {
        this.imageurl = imageurl == null ? null : imageurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.extra1
     *
     * @return the value of t_hot_news.extra1
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public String getExtra1() {
        return extra1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.extra1
     *
     * @param extra1 the value for t_hot_news.extra1
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public void setExtra1(String extra1) {
        this.extra1 = extra1 == null ? null : extra1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.extra2
     *
     * @return the value of t_hot_news.extra2
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public String getExtra2() {
        return extra2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.extra2
     *
     * @param extra2 the value for t_hot_news.extra2
     *
     * @mbggenerated Fri Oct 29 16:11:23 CST 2021
     */
    public void setExtra2(String extra2) {
        this.extra2 = extra2 == null ? null : extra2.trim();
    }
}