package client.demo.model;

import java.util.Date;

public class HotNews {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.id
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.title
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.no
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private Integer no;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.visits_real
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private String visitsReal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.visits
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private Integer visits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.time
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private Date time;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.channel
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private String channel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.id
     *
     * @return the value of t_hot_news.id
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.id
     *
     * @param id the value for t_hot_news.id
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.title
     *
     * @return the value of t_hot_news.title
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.title
     *
     * @param title the value for t_hot_news.title
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.no
     *
     * @return the value of t_hot_news.no
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.no
     *
     * @param no the value for t_hot_news.no
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setNo(Integer no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.visits_real
     *
     * @return the value of t_hot_news.visits_real
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public String getVisitsReal() {
        return visitsReal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.visits_real
     *
     * @param visitsReal the value for t_hot_news.visits_real
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setVisitsReal(String visitsReal) {
        this.visitsReal = visitsReal == null ? null : visitsReal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.visits
     *
     * @return the value of t_hot_news.visits
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public Integer getVisits() {
        return visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.visits
     *
     * @param visits the value for t_hot_news.visits
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setVisits(Integer visits) {
        this.visits = visits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.time
     *
     * @return the value of t_hot_news.time
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.time
     *
     * @param time the value for t_hot_news.time
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.channel
     *
     * @return the value of t_hot_news.channel
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public String getChannel() {
        return channel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.channel
     *
     * @param channel the value for t_hot_news.channel
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setChannel(String channel) {
        this.channel = channel == null ? null : channel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_hot_news.url
     *
     * @return the value of t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_hot_news.url
     *
     * @param url the value for t_hot_news.url
     *
     * @mbggenerated Fri Oct 29 15:08:36 CST 2021
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }
}